### ISSUE TITLE
No está documentada la marca del Fernet

### ISSUE THREAD

**Issue by saulojg** [lbrasseur/fernettest#1]
Asumimos que es Branca pero nos queda la duda sobre si es 1882 u otra, lo cual creemos que debería estar documentado.

En otro orden de cosas :) te contacto por aqui ya que estamos queriendo extender el proyecto de web services de AFIP para soportar facturas de exportación. Quisieramos consultarles cual fué el proceso que siguieron para generar las clases de Java, para tratar de acoplarnos al proyecto lo más rápido posible (hay unos cuantos generadores de WSDL hacia Java).

Cualquier cosa me pueden contactar a saulo punto gil arrroba orbital.com.ar

Un abrazo y gracias por la librería

**Comment by lbrasseur** [comment]
Depende. Marketing te va a decir que la marca es Branca, pero el departamento de testing va a decir que es 1882, jaja.

Uh, no recuerdo qué usamos para generar las clases, pero probablemente hayamos usado CXF:

https://cxf.apache.org/docs/wsdl-to-java.html

o Axis2

https://axis.apache.org/axis2/java/core/tools/CodegenToolReference.html

que eran populares en ese momento, no sé si habrá algo mejor ahora.

Buenísimo que quieran extender el proyecto!

Saludos !

**Comment by saulojg** [comment]
Nunca mejor dicho, el marketing en este rubro es una fuerza superior :)

Teniamos primero en la lista ```cfx``` y luego ```wsimport```, luego les contamos como nos fué.

Muchas gracias por responder
